### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by phamhongphuc** [phamhongphuc/uit.hotel#339]
# Roadmap Overview
This roadmap is meant to give our team and users clarity over our priorities over the next 6 months. It's meant more like a set of guidelines than as a strict set of tasks we are bound to finish. We may adjust over this period depending on changing needs and feedback from our users.

#### At a high-level, we're going to be focusing on the following these goals:

+ **Approachability** and **UX**.
+ **Productivity** through strong tooling.
+ **Infrastructure** and engineering systems.
+ Improve **workflow** process.

---

#### Permission Mixin:
+ [ ] Create simple mixin.
+ [ ] Apply in sidebar.
+ [ ] Add auto permission property.
+ [ ] Apply mixin in context & popup.

#### Rename:
+ [ ] Rename: `HiringRoom` to `RentingRoom`

---

#### Bugs:
+ [ ] Update form `@success` event.
